version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5454:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: backend
    build: ./backend
    command: sh entry.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:80"
    environment:
      - DB_NAME=myApp
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build: ./frontend
    command: sh entry.sh
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:80"
    depends_on:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    # volumes:
    #    - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "1234:80"
    restart: unless-stopped
    depends_on:
      - db