version: "3.9"
   
services:
  backend:
    build: ./backend
    command: sh entry.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:80"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
